-- Initial schema.
-- Every business table carries shop_id; Hibernate filters on it automatically (see common/tenant).
-- Money is stored as BIGINT in VND (no decimals). Times are TIMESTAMPTZ.

CREATE TABLE shops (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id        BIGINT       NOT NULL REFERENCES shops (id),
    username       VARCHAR(50)  NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    full_name      VARCHAR(100) NOT NULL,
    role           VARCHAR(20)  NOT NULL CHECK (role IN ('OWNER', 'STAFF')),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Usernames are unique across the whole system so login does not need a shop code.
    CONSTRAINT uq_users_username UNIQUE (username)
);
CREATE INDEX idx_users_shop ON users (shop_id);

CREATE TABLE menu_items (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT       NOT NULL REFERENCES shops (id),
    name        VARCHAR(100) NOT NULL,
    category    VARCHAR(50),
    price       BIGINT       NOT NULL CHECK (price >= 0),
    available   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_menu_items_shop ON menu_items (shop_id);

CREATE TABLE orders (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id       BIGINT      NOT NULL REFERENCES shops (id),
    -- Generated by the client (PWA) so an order created offline is never inserted twice on re-sync.
    client_id     UUID        NOT NULL,
    status        VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'PAID', 'CANCELLED')),
    total_amount  BIGINT      NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    note          VARCHAR(255),
    created_by    BIGINT      REFERENCES users (id),
    -- When the order was created on the device (may be long before the server sees it).
    created_at    TIMESTAMPTZ NOT NULL,
    -- When the server received it.
    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_orders_shop_client UNIQUE (shop_id, client_id)
);
CREATE INDEX idx_orders_shop_created ON orders (shop_id, created_at);

CREATE TABLE order_items (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id       BIGINT       NOT NULL REFERENCES shops (id),
    order_id      BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    -- Nullable: the menu item may be deleted later; name and price below are a snapshot.
    menu_item_id  BIGINT       REFERENCES menu_items (id) ON DELETE SET NULL,
    item_name     VARCHAR(100) NOT NULL,
    unit_price    BIGINT       NOT NULL CHECK (unit_price >= 0),
    quantity      INT          NOT NULL CHECK (quantity > 0)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_shop ON order_items (shop_id);
